<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework><OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable>
    <CelesteRoot Condition="'$(CelesteRoot)' == ''">$(CELESTE_ROOT)</CelesteRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Source/MicroblocksQolUtils.csproj"/>
    <Reference Include="Celeste"><HintPath>$(CelesteRoot)/Celeste.dll</HintPath></Reference>
    <Reference Include="FNA"><HintPath>$(CelesteRoot)/FNA.dll</HintPath></Reference>
    <Content Include="$(CelesteRoot)/*.dll" Link="%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest"/>
  </ItemGroup>
</Project>
